// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbcpdpzxrgwdlmguevsc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpiY3BkcHp4cmd3ZGxtZ3VldnNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NjI5OTEsImV4cCI6MjA2NTAzODk5MX0.UpjM5KHOshkTdidPOuECRTfDmNwnu7e1bXgK3irizzs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);